const users = [
    {
        name: "Levey",
        surname: "Denecamp",
        email: "ldenecamp0@java.com",
        username: "ldenecamp0",
        password: 'uI5?6"tiAAIK',
        account_type: "client",
        memberships: "Dogs",
    },
    {
        name: "Ethelind",
        surname: "Canton",
        email: "ecanton1@delicious.com",
        username: "ecanton1",
        password: 'vH2+7=upnb"zb',
        account_type: "administrative",
        memberships: "Machine Manager&ISO File Manager",
    },
    {
        name: "Erma",
        surname: "Gavagan",
        email: "egavagan2@godaddy.com",
        username: "egavagan2",
        password: "gI2`4BGGu+{Scz}o+#",
        account_type: "client",
        memberships: "Cats",
    },
    {
        name: "Bartholomeo",
        surname: "Vennings",
        email: "bvennings3@huffingtonpost.com",
        username: "bvennings3",
        password: "sW7=#Pq%jo?+0_",
        account_type: "administrative",
        memberships: "ISO File Manager",
    },
    {
        name: "Billy",
        surname: "Choak",
        email: "bchoak4@noaa.gov",
        username: "bchoak4",
        password: "xH3\\tDWLy@OS~*a",
        account_type: "client",
        memberships: "Dogs",
    },
    {
        name: "Laverna",
        surname: "Pendrid",
        email: "lpendrid5@lulu.com",
        username: "lpendrid5",
        password: "lN5!2an}%ChE<>/",
        account_type: "client",
        memberships: "Dogs",
    },
    {
        name: "Carly",
        surname: "Gingedale",
        email: "cgingedale6@sbwire.com",
        username: "cgingedale6",
        password: "uB3_I&k,Jo}nDD",
        account_type: "client",
        memberships: "Dogs",
    },
    {
        name: "Garret",
        surname: "Bryett",
        email: "gbryett7@altervista.org",
        username: "gbryett7",
        password: "hQ3+FD&$&)6fsmDDUz",
        account_type: "client",
        memberships: "Cats",
    },
    {
        name: "Franni",
        surname: "McCurley",
        email: "fmccurley8@desdev.cn",
        username: "fmccurley8",
        password: "zD4`zsf6Nno<IAZCkOr",
        account_type: "administrative",
        memberships: "Machine Manager",
    },
    {
        name: "Efren",
        surname: "Shilburne",
        email: "eshilburne9@homestead.com",
        username: "eshilburne9",
        password: "yM2=2=#qh92s}O9",
        account_type: "client",
        memberships: "Dogs",
    },
    {
        name: "Bernhard",
        surname: "Gowthrop",
        email: "bgowthropa@flickr.com",
        username: "bgowthropa",
        password: "uP8(Pn*2f%Fdp",
        account_type: "client",
        memberships: "Cats",
    },
    {
        name: "Beck",
        surname: "Feldon",
        email: "bfeldonb@ucoz.ru",
        username: "bfeldonb",
        password: "xZ2,J/Lq{W",
        account_type: "administrative",
        memberships: "Machine Manager&ISO File Manager",
    },
    {
        name: "Sissy",
        surname: "Cruickshank",
        email: "scruickshankc@delicious.com",
        username: "scruickshankc",
        password: "wP1&f,VOHBrMWvT8",
        account_type: "administrative",
        memberships: "Machine Manager",
    },
    {
        name: "Walt",
        surname: "Gawn",
        email: "wgawnd@webmd.com",
        username: "wgawnd",
        password: "rM3}j\"l)ZYjxuuhn$F'O",
        account_type: "administrative",
        memberships: "Machine Manager&ISO File Manager",
    },
    {
        name: "Kathrine",
        surname: "Comino",
        email: "kcominoe@indiegogo.com",
        username: "kcominoe",
        password: "cZ2){S=>B+BC=M(<&i",
        account_type: "client",
        memberships: "Cats",
    },
    {
        name: "Horacio",
        surname: "Mealham",
        email: "hmealhamf@myspace.com",
        username: "hmealhamf",
        password: "oD0\"cs3r7V('<\\Afg5",
        account_type: "client",
        memberships: "Cats",
    },
    {
        name: "Jan",
        surname: "Ruhben",
        email: "jruhbeng@uol.com.br",
        username: "jruhbeng",
        password: "aK6/lEmQX.aiEFGFeU&",
        account_type: "client",
        memberships: "Dogs",
    },
    {
        name: "Celisse",
        surname: "Benoit",
        email: "cbenoith@zdnet.com",
        username: "cbenoith",
        password: 'pF4?saJW"Ve',
        account_type: "administrative",
        memberships: "Machine Manager",
    },
    {
        name: "Magdalene",
        surname: "Loveguard",
        email: "mloveguardi@hostgator.com",
        username: "mloveguardi",
        password: "dV7{0}>Q0=7{T",
        account_type: "client",
        memberships: "Cats&Dogs",
    },
    {
        name: "Obed",
        surname: "Gare",
        email: "ogarej@ning.com",
        username: "ogarej",
        password: "cB5/r5<AZ.#xA",
        account_type: "administrative",
        memberships: "Machine Manager&ISO File Manager",
    },
];

export default users;
